services:
  testy:
    image: ghcr.io/victorbitancourt/testy:latest
    ports:
      - "3000:80"
    environment:
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
      SOLID_QUEUE_IN_PUMA: "true"
    volumes:
      - testy_storage:/rails/storage
    restart: unless-stopped

volumes:
  testy_storage:
